### ISSUE TITLE
strongly signing anglesharp.diffing

### ISSUE THREAD

**Issue by egil** [AngleSharp/AngleSharp.Diffing#11]
As the other AngleSharp packages are strongly signed, and bUnit users wants it to be that too, I think its time to strongly name diffing as well.

@FlorianRappl do we have a joint key we're using here, and is there anything I need to be aware of wrt setting this up here?

Related: https://github.com/egil/bUnit/issues/316

**Comment by FlorianRappl** [comment]
Yes we always use this one IIRC: https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Key.snk

I think it "should just work".

**Comment by FlorianRappl** [comment]
I'd also make a PR to bring this project to GitHub actions.

We are in the process of migrating all projects as the AppVeyor system stopped working and was also a pain to keep maintained.

Would that be fine with you?

**Comment by egil** [comment]
Absolutely. Dont hold back. Would also be cool to get Diffing added to the official website. It seems pretty stable by now :)

**Comment by FlorianRappl** [comment]
Ah yeah. Good pointer with the website!

**Comment by FlorianRappl** [comment]
Website done!

https://anglesharp.github.io/projects.html

**Comment by FlorianRappl** [comment]
Done -> I pushed directly into the `devel` branch and a preview was build.

I also changed the default branch to `devel` (this is now the default branch for all AngleSharp projects) and renamed `dev` -> `devel`. That way its just consistent with the other repositories. I hope that's fine, otherwise we can revert (this way we could also just re-apply the `GitBase` repo without requiring a change here).

I've added your name to the funding.

**Comment by egil** [comment]
Thank you Florian.

Im all for keeping things consistent, and dont mind different paradigmes between projects, I'm used to that from working with different customers :)

Did you add the key signing as well?

**Comment by FlorianRappl** [comment]
Nope - let me just do that, too!

**Comment by FlorianRappl** [comment]
Key added and pushed. Hope I did not screw up ...

**Comment by egil** [comment]
Something broke in the build. Ill take a look at it. Can also update the references to use the just released anglesharp 0.15

**Comment by egil** [comment]
Seems like it works correctly now. Thank you for your help @FlorianRappl!
