### ISSUE TITLE
IDiff should just implement ToString()

### ISSUE THREAD

**Issue by SebastianStehle** [AngleSharp/AngleSharp.Diffing#22]
# New Feature Proposal

## Description

IDiff should just implement ToString() instead of DebuggerDisplay.

## Background

I would like to render all diffs in my unit tests but it would be a lot of unnecessary effort because IDiff does not have a string representation.

**Comment by egil** [comment]
I dont necessarily see anything bad about moving the contents of the DebuggerDisplay attributes on the IDiff types into a ToString() overload. But I am unsure of we can come up with "the one way" to print out diffs that will suite all peoples needs, so I am not sure the value is there.

In bUnit, I have the following method for printing out diffs from a comparison during testing. Perhaps you an use that as inspiration for your project: https://github.com/bUnit-dev/bUnit/blob/main/src/bunit.web/Asserting/HtmlEqualException.cs#L28

**Comment by SebastianStehle** [comment]
This helps as well :)

**Comment by egil** [comment]
Great. I am going to close this issue in that case.
