### ISSUE TITLE
No possibility to check for newly created HTML attribute

### ISSUE THREAD

**Issue by desmondische** [AngleSharp/AngleSharp.Diffing#29]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

If HTML attribute is added dynamically, you can’t check for addition using existing methods like `ShouldBeAddition` or `ShouldBeAttributeChange`.

https://stackoverflow.com/questions/75345362/bunit-check-for-attribute-addition

**Comment by egil** [comment]
This belongs in the bUnit repo. Please move the issue over there, thanks, and the maintainers there will take a look.
