### ISSUE TITLE
diff:ignoreChildren does not Ignore Children of a Button

### ISSUE THREAD

**Issue by japhelps** [AngleSharp/AngleSharp.Diffing#43]
# Bug Report

## Prerequisites

- [ X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [ X] Are you running the latest version of AngleSharp? `(0.18.2)`
- [ X] Did you check the FAQs to see if that helps you?
- [ X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [ X] Did you perform a search in the issues?

## Description

Using `diff:ignoreChildren` does not ignore child elements or text of a `button`

## Steps to Reproduce
The following test does not pass, but from what I understand of the [documentation](https://github.com/AngleSharp/AngleSharp.Diffing/wiki/Diffing-Options#filter-strategies) it should pass.
```
public class AngleSharpTests
{
    private readonly ITestOutputHelper output;

    public AngleSharpTests(ITestOutputHelper output)
    {
        this.output = output;
    }

    [Theory]
    [InlineData(@"<button id=""buttonid"" class=""somecss"">Not Ignored</button>")]
    [InlineData(@"<button id=""buttonid"" class=""somecss""><span>Not Ignored</span></button>")]
    public void GivenButton_MarkupMatches(string actual)
    {
        var control = @"<button diff:ignoreAttributes diff:ignoreChildren></button>";

        var diffs = DiffBuilder.Compare(control)
            .WithTest(actual)
            .Build();

        foreach (var diff in diffs)
            output.WriteLine(diff.ToString());

        Assert.False(diffs.Any());
    }
}
```

**Expected behavior:** The test should pass

**Actual behavior:** The test fails

**Environment details:** Windows 11, .NET 8

## Possible Solution

The only way I have found to get the test to succeed is to change the button expected HTML to the following
`<button diff:ignoreAttributes><span diff:ignoreChildren></span></button>`

**Comment by egil** [comment]
Thanks for the repro. I will take a look and get back to you.

**Comment by egil** [comment]
This should be fixed in v1 that is being published right now.
